package com.ims.common.service.user;

import com.ims.common.model.base.user.BaseSRole;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SRole extends BaseSRole<SRole> {
	public static final SRole dao = new SRole().dao();
	
	public Page<SRole> paginate(int pageNumber, int pageSize,String condition) {
		return paginate(pageNumber, pageSize, "select *", "from s_role " + condition + " order by id desc");
	}
}
