package com.ims.common.service.user;

import com.ims.common.model.base.user.BaseSRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SRole extends BaseSRole<SRole> {
	public static final SRole dao = new SRole().dao();
}
