package com.ims.common.service.user;

import com.ims.common.model.Blog;
import com.ims.common.model.base.user.BaseSUser;
import com.jfinal.plugin.activerecord.Page;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SUser extends BaseSUser<SUser> {
	public static final SUser dao = new SUser().dao();
	
	public Page<SUser> paginate(int pageNumber, int pageSize,String condition) {
		return paginate(pageNumber, pageSize, "select *", "from s_user " + condition + " order by id desc");
	}
}
