package com.ims.common.service.user;

import com.ims.common.model.base.user.BaseSUser;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SUser extends BaseSUser<SUser> {
	public static final SUser dao = new SUser().dao();
}
