package com.ims.common.service;

import com.ims.common.model.base.BaseBuyIn;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BuyIn extends BaseBuyIn<BuyIn> {
	public static final BuyIn dao = new BuyIn().dao();
	

	public Page<BuyIn> paginate(int pageNumber, int pageSize,String condition) {
		return paginate(pageNumber, pageSize, "select *", "from buy_in " + condition + " order by id desc");
	}
}
