package com.ims.common.service;

import com.ims.common.model.base.BaseSalesOut;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SalesOut extends BaseSalesOut<SalesOut> {
	public static final SalesOut dao = new SalesOut().dao();
	
	public Page<SalesOut> paginate(int pageNumber, int pageSize,String condition) {
		return paginate(pageNumber, pageSize, "select *", "from sales_out " + condition + " order by id desc");
	}
}
