package com.ims.common.service;

import com.ims.common.model.base.BaseSDic;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SDic extends BaseSDic<SDic> {
	public static final SDic dao = new SDic().dao();
}
