package com.ims.common.service;

import com.ims.common.model.base.BaseSResource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SResource extends BaseSResource<SResource> {
	public static final SResource dao = new SResource().dao();
}
