package com.ims.common.service;

import com.ims.common.model.base.BaseSRoleright;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SRoleright extends BaseSRoleright<SRoleright> {
	public static final SRoleright dao = new SRoleright().dao();
}
