package com.ims.common.service;

import com.ims.common.model.base.BaseSRoleuser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SRoleuser extends BaseSRoleuser<SRoleuser> {
	public static final SRoleuser dao = new SRoleuser().dao();
}
