package com.ims.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSalesOut<M extends BaseSalesOut<M>> extends Model<M> implements IBean {

	public M setPrdName(java.lang.String prdName) {
		set("prd_name", prdName);
		return (M)this;
	}

	public java.lang.String getPrdName() {
		return get("prd_name");
	}

	public M setDriver(java.lang.String driver) {
		set("driver", driver);
		return (M)this;
	}

	public java.lang.String getDriver() {
		return get("driver");
	}

	public M setCarNo(java.lang.String carNo) {
		set("car_no", carNo);
		return (M)this;
	}

	public java.lang.String getCarNo() {
		return get("car_no");
	}

	public M setCountNum(java.lang.Long countNum) {
		set("count_num", countNum);
		return (M)this;
	}

	public java.lang.Long getCountNum() {
		return get("count_num");
	}

	public M setXuCount(java.lang.Long xuCount) {
		set("xu_count", xuCount);
		return (M)this;
	}

	public java.lang.Long getXuCount() {
		return get("xu_count");
	}

	public M setGiveCount(java.lang.Long giveCount) {
		set("give_count", giveCount);
		return (M)this;
	}

	public java.lang.Long getGiveCount() {
		return get("give_count");
	}

	public M setBuyerName(java.lang.String buyerName) {
		set("buyer_name", buyerName);
		return (M)this;
	}

	public java.lang.String getBuyerName() {
		return get("buyer_name");
	}

	public M setInputDate(java.lang.String inputDate) {
		set("input_date", inputDate);
		return (M)this;
	}

	public java.lang.String getInputDate() {
		return get("input_date");
	}

	public M setInputTime(java.lang.String inputTime) {
		set("input_time", inputTime);
		return (M)this;
	}

	public java.lang.String getInputTime() {
		return get("input_time");
	}

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public M setCarType(java.lang.Integer carType) {
		set("car_type", carType);
		return (M)this;
	}

	public java.lang.Integer getCarType() {
		return get("car_type");
	}

}
