package com.ims.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSRoleright<M extends BaseSRoleright<M>> extends Model<M> implements IBean {

	public M setRoleId(java.lang.Long roleId) {
		set("role_id", roleId);
		return (M)this;
	}

	public java.lang.Long getRoleId() {
		return get("role_id");
	}

	public M setResourceId(java.lang.Long resourceId) {
		set("resource_id", resourceId);
		return (M)this;
	}

	public java.lang.Long getResourceId() {
		return get("resource_id");
	}

	public M setOpFlg(java.lang.Integer opFlg) {
		set("op_flg", opFlg);
		return (M)this;
	}

	public java.lang.Integer getOpFlg() {
		return get("op_flg");
	}

}
