package com.ims.common.model.base;

import java.math.BigDecimal;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBuyIn<M extends BaseBuyIn<M>> extends Model<M> implements IBean {
	
	public M setDriver(java.lang.String driver) {
		set("driver", driver);
		return (M)this;
	}

	public java.lang.String getDriver() {
		return get("driver");
	}
	
	public M setBuyType(java.lang.Integer buyType) {
		set("buy_type", buyType);
		return (M)this;
	}

	public java.lang.Integer getBuyType() {
		return get("buy_type");
	}
	
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public M setInputDate(java.lang.String inputDate) {
		set("input_date", inputDate);
		return (M)this;
	}

	public java.lang.String getInputDate() {
		return get("input_date");
	}

	public M setInputTime(java.lang.String inputTime) {
		set("input_time", inputTime);
		return (M)this;
	}

	public java.lang.String getInputTime() {
		return get("input_time");
	}

	public M setCarNo(java.lang.String carNo) {
		set("car_no", carNo);
		return (M)this;
	}

	public java.lang.String getCarNo() {
		return get("car_no");
	}

	public M setMaoHeavy(BigDecimal maoHeavy) {
		set("mao_heavy", maoHeavy);
		return (M)this;
	}

	public BigDecimal getMaoHeavy() {
		return get("mao_heavy");
	}

	public M setPiHeavy(BigDecimal piHeavy) {
		set("pi_heavy", piHeavy);
		return (M)this;
	}

	public BigDecimal getPiHeavy() {
		return get("pi_heavy");
	}

	public M setJinHeavy(BigDecimal jinHeavy) {
		set("jin_heavy", jinHeavy);
		return (M)this;
	}

	public BigDecimal getJinHeavy() {
		return get("jin_heavy");
	}

	public M setSalerName(java.lang.String salerName) {
		set("saler_name", salerName);
		return (M)this;
	}

	public java.lang.String getSalerName() {
		return get("saler_name");
	}

}
