package com.ims.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSUser<M extends BaseSUser<M>> extends Model<M> implements IBean {
	
	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setLoginName(java.lang.String loginName) {
		set("login_name", loginName);
		return (M)this;
	}

	public java.lang.String getLoginName() {
		return get("login_name");
	}

	public M setLoginPasswd(java.lang.String loginPasswd) {
		set("login_passwd", loginPasswd);
		return (M)this;
	}

	public java.lang.String getLoginPasswd() {
		return get("login_passwd");
	}
	
	public M setInputTime(java.lang.String inputTime) {
		set("input_time", inputTime);
		return (M)this;
	}

	public java.lang.String getsetInputTime() {
		return get("input_time");
	}

}
