package com.ims.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSDic<M extends BaseSDic<M>> extends Model<M> implements IBean {

	public M setEn(java.lang.String en) {
		set("en", en);
		return (M)this;
	}

	public java.lang.String getEn() {
		return get("en");
	}

	public M setCh(java.lang.String ch) {
		set("ch", ch);
		return (M)this;
	}

	public java.lang.String getCh() {
		return get("ch");
	}

	public M setOp(java.lang.String op) {
		set("op", op);
		return (M)this;
	}

	public java.lang.String getOp() {
		return get("op");
	}

	public M setDemo(java.lang.String demo) {
		set("demo", demo);
		return (M)this;
	}

	public java.lang.String getDemo() {
		return get("demo");
	}

}
